### PR TITLE
Fix FacilityInterceptor to allow access to ping endpoint

### LINKED ISSUE #265: Fix ping endpoint
Recently implemented facility interceptor produces a NullPointerException when requesting ping endpoint.

### PR DESCRIPTION
**Pull request by villejuutila**
Resolves #265

### CODE REVIEW

File: src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java [hunk 1]
```diff
@@ -26,19 +27,28 @@ public void filter(ContainerRequestContext requestContext) throws IOException {
...
         MultivaluedMap<String, String> pathParameters  = uriInfo.getPathParameters();
-        Optional<String> facility = pathParameters.get(FACILITY).stream().findFirst();
+        List<String> facilityParams = pathParameters.get(FACILITY);
+        CollectionUtils.filter(facilityParams, PredicateUtils.notNullPredicate());
+
+        if (facilityParams == null && Arrays.asList(WHITELISTED_PATHS).contains(path)) {
+            return;
+        }
+
+        if (facilityParams == null) {
```
Comment (hkurhinen) [inline src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java:37]: Doesn't this check include all the conditions of previous one + some extra?

**Review by hkurhinen — CHANGES_REQUESTED** [review]

File: src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java (hunk 1 above)
Comment (villejuutila) [reply src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java:33]: Resolved
